# -*- coding: utf-8 -*-
"""PRs (Checker).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ni1reHAxHxY70uVaWWMd7XRuvwDoC6wa
"""

!pip install PyGithub

"""# Git users "username" input code block"""

import base64
from github import Github
from pprint import pprint

# Enter a github user's name
usr = str(input("Enter Username: "))

# Github username
username = usr

# pygithub object
g = Github()

# get that user by username
user = g.get_user(username)

for repo in user.get_repos():
    print(repo)

"""# Function to extract some useful information from this Repository object:"""

def print_repo(repo):
    # repository full name
    print("Full name:", repo.full_name)
    # repository description
    print("Description:", repo.description)
    # the date of when the repo was created
    print("Date created:", repo.created_at)
    # the date of the last git push
    print("Date of last push:", repo.pushed_at)
    # home website (if available)
    print("Home Page:", repo.homepage)
    # programming language
    print("Language:", repo.language)
    # number of forks
    print("Number of forks:", repo.forks)
    # number of stars
    print("Number of stars:", repo.stargazers_count)
    print("-"*50)
    # repository content (files & directories)
    print("Contents:")
    
    for content in repo.get_contents(""):
        print(content)
    try:
        # repo license
        print("License:", base64.b64decode(repo.get_license().content.encode()).decode())
    except:
        pass

"""# Iterate over all public repositories"""

# iterate over all public repositories
for repo in user.get_repos():
  print()
  print_repo(repo)
  print()
  print("="*100)